spring:
  application.name: HYPR

  springdoc.swagger-ui.path: /swagger-ui.html

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4-turbo
        temperature: 0.7

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.yaml